name: Integration test
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v3
          with:
            path: |
              ~/.platformio
              ~/.cache/pip
            key: ${{ runner.os }}-pio

        - name: Create Passwords.h
          run: |
            echo "#define g_ssid \"${{ secrets.WIFI_SSID }}\"" > esp32/lib/WifiSetup/Passwords.h
            echo "#define g_password \"${{ secrets.WIFI_PASSWORD }}\"" >> esp32/lib/WifiSetup/Passwords.h

        - name: Run PlatformIO tests 
          run: |
            cd esp32
            ls lib/WifiSetup
            pio test