name: Integration test
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
        - uses: actions/checkout@v4

        - name: Create Passwords.h
          run: |
            echo "#define g_ssid \"${{ secrets.WIFI_SSID }}\"" > esp32/lib/WifiSetup/Passwords.h
            echo "#define g_password \"${{ secrets.WIFI_PASSWORD }}\"" >> esp32/lib/WifiSetup/Passwords.h

        - name: Run PlatformIO tests 
          shell: bash
          run: |
            cd esp32
            ~/.platformio/penv/bin/pio test
